# Generated by Django 4.1.4 on 2022-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_doa'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquran',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
